version: '2'

services:
  server:
    container_name: ndncert-server
    image: ndncert-server
    networks:
      ndn-network:
        ipv4_address: $SERVER_IP
  
  client:
    container_name: ndncert-client
    image: ndncert-client
    networks:
      ndn-network:
        ipv4_address: $CLIENT_IP

  server-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.4
    container_name: server-agent
    entrypoint: /bin/bash
    command: ["-c",
      "aca-py start \
        --label server.agent \
        --admin '0.0.0.0' ${SERVER_AGENT_ADMIN_PORT} \
        --admin-insecure-mode \
        --auto-provision \
        --debug-connections \
        --endpoint http://${SERVER_AGENT_IP}:${SERVER_AGENT_INBOUND_PORT} \
        --genesis-url ${LEDGER_URL}/genesis \
        --inbound-transport http '0.0.0.0' ${SERVER_AGENT_INBOUND_PORT} \
        --outbound-transport http \
        --public-invites \
        --seed ${SERVER_SEED}
        --wallet-key abc \
        --wallet-name swallet \
        --wallet-storage-type default \
        --wallet-type indy \
        --log-level INFO \
        --auto-accept-requests \
        --auto-store-credential
      "
    ]
    ports:
      - "${SERVER_AGENT_ADMIN_PORT}:${SERVER_AGENT_ADMIN_PORT}"
      - "${SERVER_AGENT_INBOUND_PORT}:${SERVER_AGENT_INBOUND_PORT}"
    networks:
      ndn-network:
        ipv4_address: $SERVER_AGENT_IP

  client-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.4
    container_name: client-agent
    entrypoint: /bin/bash
    command: ["-c",
      "aca-py start \
        --label client.agent \
        --admin '0.0.0.0' ${CLIENT_AGENT_ADMIN_PORT} \
        --admin-insecure-mode \
        --auto-provision \
        --debug-connections \
        --endpoint http://${CLIENT_AGENT_IP}:${CLIENT_AGENT_INBOUND_PORT} \
        --genesis-url ${LEDGER_URL}/genesis \
        --inbound-transport http '0.0.0.0' ${CLIENT_AGENT_INBOUND_PORT} \
        --outbound-transport http \
        --public-invites \
        --seed ${CLIENT_SEED} \
        --wallet-key abc \
        --wallet-name cwallet \
        --wallet-storage-type default \
        --wallet-type indy \
        --log-level INFO \
        --auto-accept-requests \
        --auto-store-credential
      "
    ]
    ports:
      - "${CLIENT_AGENT_ADMIN_PORT}:${CLIENT_AGENT_ADMIN_PORT}"
      - "${CLIENT_AGENT_INBOUND_PORT}:${CLIENT_AGENT_INBOUND_PORT}"
    networks:
      ndn-network:
        ipv4_address: $CLIENT_AGENT_IP

networks:
  ndn-network:
    driver: bridge
    ipam:
      config:
        - subnet: $SUBNET_IP
          gateway: $SUBNET_GATEWAY